### PR TITLE
Added composer.json

### PR DESCRIPTION
**Pull request by chadrien**
So the module can be installed via composer and added the the Magento composer repository (http://packages.firegento.com/)

TODO: change the `tobedefined` values after merge.

### CODE REVIEW

**Comment by Skrath** [comment]
Nice! I never got around to looking into the composer requirements as most of our work is in private repos.

**Comment by grantkemp** [comment]
+1 for this .. Looks great

**Comment by chadrien** [comment]
Not sure if it's a big deal or not, but you have the `type` twice (l. 5 and 8)

**Comment by chadrien** [comment]
I've PR the firegento composer repository so we will be able to install the module with composer :smiley: 

https://github.com/magento-hackathon/composer-repository/pull/252

**Pull request merged**
